<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>UPPERIOC</RootNamespace>
    <LangVersion>preview</LangVersion>

        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
	<Import Project="$(MSBuildThisFileDirectory)targets\upperioc.targets" />
	<Import Project="$(MSBuildThisFileDirectory)targets\upperioc.props" />

	  <ItemGroup>
    <PackageReference Include="IOCG" Version="1.0.0" />
    <PackageReference Include="System.Management" Version="4.6.0" />
  </ItemGroup>


<PropertyGroup>
  <Version>2.0.1.13</Version>
  <PackageId>UPPERIOC</PackageId>
  <Authors>Net Wsp</Authors>
  <Description>一个自带插件的IOC容器</Description>
</PropertyGroup>
<ItemGroup Label="Package">

    <None Include="targets\upperioc.targets" PackagePath="build\netstandard2.0" Pack="true" />
    <None Include="targets\upperioc.props" PackagePath="build\netstandard2.0" Pack="true" />
   <None Include="targets\upperioc.targets" PackagePath="buildTransitive\netstandard2.0" Pack="true" />
    <None Include="targets\upperioc.props" PackagePath="buildTransitive\netstandard2.0" Pack="true" />

    
  <None Include="..\IOCCodeGenerator\bin\$(Configuration)\netstandard2.0\IOCCodeGenerator.dll">
    <Pack>true</Pack>
    <PackagePath>analyzers\dotnet\roslyn3.8\cs</PackagePath>
  </None>
  <None Include="..\UPPERIOC\bin\$(Configuration)\netstandard2.0\UPPERIOC.dll">
    <Pack>true</Pack>
    <PackagePath>analyzers\dotnet\roslyn3.8\cs</PackagePath>
  </None>
  <None Include="..\UPPERIOC\bin\$(Configuration)\netstandard2.0\UPPERIOC.dll" Pack="true" PackagePath="lib\netstandard2.0" />
    <None Include="..\UPPERIOC\bin\$(Configuration)\net462\UPPERIOC.dll" Pack="true" PackagePath="lib\net462" />
</ItemGroup>
  <ItemGroup>

    <ProjectReference Include="..\IOCCodeGenerator\IOCCodeGenerator.csproj" ReferenceOutputAssembly="false" />
   </ItemGroup>


		
	<PropertyGroup>
  <IncludeBuildOutput>true</IncludeBuildOutput>
  <IsRoslynAnalyzer>true</IsRoslynAnalyzer>
  <SignAssembly>True</SignAssembly>
  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  <EnableNETAnalyzers>True</EnableNETAnalyzers>
  <AnalysisLevel>latest</AnalysisLevel>
  <Nullable>enable</Nullable>
  <PackageOutputPath>C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\</PackageOutputPath>
  <Title>UPPERIOC</Title>
  <NeutralLanguage>zh-Hans</NeutralLanguage>
  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  <IncludeSymbols>true</IncludeSymbols>
  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  <PackageReadmeFile>README.md</PackageReadmeFile>
  <PackAsTool>true</PackAsTool>
  <PackageProjectUrl>https://gitee.com/laowangm_m/upper-com-auto-test</PackageProjectUrl>
  <PackageIcon>9200301643_fef33a95-3a3c-41a9-8d72-f3aa5d0c74dd.png</PackageIcon>
  <RepositoryUrl>https://gitee.com/laowangm_m/upper-com-auto-test</RepositoryUrl>
  <RepositoryType>gitee</RepositoryType>
  <PackageTags>ioc</PackageTags>
  <PackageReleaseNotes>初始版本</PackageReleaseNotes>
  <ImplicitUsings>enable</ImplicitUsings>
  <NuGetAudit>False</NuGetAudit>
  <AssemblyVersion>2.0.0</AssemblyVersion>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net461|AnyCPU'">
  <DebugType>embedded</DebugType>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net461|AnyCPU'">
  <DebugType>embedded</DebugType>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net462|AnyCPU'">
  <DebugType>embedded</DebugType>
  <Optimize>True</Optimize>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net462|AnyCPU'">
  <DebugType>embedded</DebugType>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
  <Optimize>True</Optimize>
</PropertyGroup>
<ItemGroup>
  <None Include="..\README.md">
    <Pack>True</Pack>
    <PackagePath>\</PackagePath>
  </None>
  <None Include="D:\Users\Wsp00\Pictures\9200301643_fef33a95-3a3c-41a9-8d72-f3aa5d0c74dd.png">
    <Pack>True</Pack>
    <PackagePath>\</PackagePath>
  </None>
</ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
