<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>UPPERIOC2</RootNamespace>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <TargetFramework>net45</TargetFramework>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Optimize>False</Optimize>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>True</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="5.0.0" />
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
  </ItemGroup>

</Project>
