name: ✨ 功能请求 Feature
description: 请求添加一个新的功能
title: "[Feature] 简要描述功能"
labels: ["feature"]
body:
  - type: textarea
    id: feature-desc
    attributes:
      label: 功能描述
      description: 请详细描述你希望添加的功能是什么，以及为什么它很重要
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: 使用场景
      description: 请描述该功能会在哪些场景下被使用，有无替代方案
    validations:
      required: false
  - type: input
    id: priority
    attributes:
      label: 优先级（可选）
      placeholder: high / medium / low
