<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
   <ImplicitUsings>enable</ImplicitUsings>
 
    <OutputType>Library</OutputType>
    <TargetFramework>net462</TargetFramework>
    <RootNamespace>FrmControl</RootNamespace>
    <AssemblyName>FrmControl</AssemblyName>
    <UseWindowsForms>True</UseWindowsForms>
    <FileAlignment>512</FileAlignment> 
<IsPackable>true</IsPackable>
<EnableDefaultCompileItems>false</EnableDefaultCompileItems>
<EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
<LangVersion>preview</LangVersion>

    </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>

    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>embedded</DebugType>

    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <StartupObject />
    <PackageOutputPath>C:\Program Files (x86)\Microsoft SDKs\NuGetPackages</PackageOutputPath>
    <Version>1.0.0.35</Version>

  </PropertyGroup>
  <ItemGroup>

    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Management" />
    <Reference Include="System.Numerics" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Data" />

    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Animation\AnimationBase.cs" />
    <Compile Include="Animation\ClickAnimation.cs" />
    <Compile Include="C\Btn\Apple3Btn.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="C\Btn\Apple3Btn.Designer.cs">
      <DependentUpon>Apple3Btn.cs</DependentUpon>
    </Compile>
    <Compile Include="C\Btn\FrmBtn.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="C\Btn\FrmBtnImg.cs" />
    <Compile Include="C\Btn\FrmBtnImg.Designer.cs" />
    <Compile Include="C\Btn\FrmLinerGidentBtn.cs" />
    <Compile Include="C\Btn\FrmLinerGidentBtn.Designer.cs">
      <DependentUpon>FrmLinerGidentBtn.cs</DependentUpon>
    </Compile>
    <Compile Include="C\Btn\SliderCtl.cs" />
    <Compile Include="C\CBaseControl.cs" />
    <Compile Include="C\LastResultControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="C\LastResultControl.Designer.cs">
      <DependentUpon>LastResultControl.cs</DependentUpon>
    </Compile>
    <Compile Include="C\SystemStopwatch.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="C\TempForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="C\TempShow\TempListForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="C\TempShow\TempListForm.Designer.cs">
      <DependentUpon>TempListForm.cs</DependentUpon>
    </Compile>
    <Compile Include="Extention\GraphicsExtensions.cs" />
    <Compile Include="FrmBase\FrmBaseForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmBase\FrmBaseForm.Designer.cs">
      <DependentUpon>FrmBaseForm.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmPremission\BLL\FrmEditCBLL.cs" />
    <Compile Include="FrmPremission\BLL\FrmRoleGroupbll.cs" />
    <Compile Include="FrmPremission\BLL\FrmRoleEditBLL.cs" />
    <Compile Include="FrmPremission\BLL\PremissionBLL.cs" />
    <Compile Include="FrmPremission\C\RoleGroupEditControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="FrmPremission\C\RoleGroupEditControl.Designer.cs">
      <DependentUpon>RoleGroupEditControl.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmPremission\C\RoleEditControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="FrmPremission\C\RoleEditControl.Designer.cs">
      <DependentUpon>RoleEditControl.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmPremission\FrmRoleEdit.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmPremission\FrmRoleEdit.Designer.cs">
      <DependentUpon>FrmRoleEdit.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmPremission\FrmUserGroupEdit.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmPremission\FrmUserGroupEdit.Designer.cs">
      <DependentUpon>FrmUserGroupEdit.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmPwd.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmPwd.Designer.cs">
      <DependentUpon>FrmPwd.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmInput.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmInput.Designer.cs">
      <DependentUpon>FrmInput.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmSelect.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmSelect.Designer.cs">
      <DependentUpon>FrmSelect.cs</DependentUpon>
    </Compile>
    <Compile Include="Frm\FrmDialog.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Frm\FrmDialog.Designer.cs">
      <DependentUpon>FrmDialog.cs</DependentUpon>
    </Compile>
    <Compile Include="C\GradientProgressBar.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Include="C\GradientProgressBar.Designer.cs">
      <DependentUpon>GradientProgressBar.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmPremission\FrmUserEdit.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmPremission\FrmUserEdit.Designer.cs">
      <DependentUpon>FrmUserEdit.cs</DependentUpon>
    </Compile>
    <Compile Include="Loading.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="Loading.Designer.cs">
      <DependentUpon>Loading.cs</DependentUpon>
    </Compile>
    <Compile Include="C\LoadingControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="C\LoadingControl.Designer.cs">
      <DependentUpon>LoadingControl.cs</DependentUpon>
    </Compile>
    <Compile Include="Model\CountModel - 复制.cs" />
    <Compile Include="Model\CountModel.cs" />
    <Compile Include="Model\PNCountModel.cs" />
    <Compile Include="MyTips.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="MyTips.Designer.cs">
      <DependentUpon>MyTips.cs</DependentUpon>
    </Compile>
    <Compile Include="Properties\AssemblyInfo.cs" />
    <Compile Include="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Include="FrmPremission\PremissionEditForm.cs">
      <SubType>Form</SubType>
    </Compile>
    <Compile Include="FrmPremission\PremissionEditForm.Designer.cs">
      <DependentUpon>PremissionEditForm.cs</DependentUpon>
    </Compile>
    <Compile Include="FrmPremission\C\UserEditControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Include="FrmPremission\C\UserEditControl.Designer.cs">
      <DependentUpon>UserEditControl.cs</DependentUpon>
    </Compile>
    <Compile Include="Util\WindowUtil.cs" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="C\Btn\Apple3Btn.resx">
      <DependentUpon>Apple3Btn.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="C\Btn\FrmBtnImg.resx" />
    <EmbeddedResource Include="C\Btn\FrmLinerGidentBtn.resx">
      <DependentUpon>FrmLinerGidentBtn.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="C\LastResultControl.resx">
      <DependentUpon>LastResultControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="C\TempForm.resx" />
    <EmbeddedResource Include="C\TempShow\TempListForm.resx">
      <DependentUpon>TempListForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmBase\FrmBaseForm.resx">
      <DependentUpon>FrmBaseForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPremission\C\RoleGroupEditControl.resx">
      <DependentUpon>RoleGroupEditControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPremission\C\RoleEditControl.resx">
      <DependentUpon>RoleEditControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPremission\FrmRoleEdit.resx">
      <DependentUpon>FrmRoleEdit.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPremission\FrmUserGroupEdit.resx">
      <DependentUpon>FrmUserGroupEdit.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPwd.resx">
      <DependentUpon>FrmPwd.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmInput.resx">
      <DependentUpon>FrmInput.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmSelect.resx">
      <DependentUpon>FrmSelect.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Frm\FrmDialog.resx">
      <DependentUpon>FrmDialog.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="C\GradientProgressBar.resx">
      <DependentUpon>GradientProgressBar.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPremission\FrmUserEdit.resx">
      <DependentUpon>FrmUserEdit.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Loading.resx">
      <DependentUpon>Loading.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="C\LoadingControl.resx">
      <DependentUpon>LoadingControl.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="MyTips.resx">
      <DependentUpon>MyTips.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPremission\PremissionEditForm.resx">
      <DependentUpon>PremissionEditForm.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Include="FrmPremission\C\UserEditControl.resx">
      <DependentUpon>UserEditControl.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Include="app.config" />
    <None Include="Resources\取消.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\用户.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\实验室监控.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Maximize-2.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Minimize-2.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Resources\Shut down-2.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="IOCG" Version="1.0.0.2" />
    <PackageReference Include="System.ValueTuple">
      <Version>4.5.0</Version>
    </PackageReference>
    <PackageReference Include="UPPERIOC" Version="2.0.4.10" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="nuget push -Source &quot;http://8.138.99.154:5000/v3/index.json&quot; -ApiKey &quot;wspwasnl001112&quot; &quot;$(PackageOutputPath)\$(PackageId).$(Version).nupkg&quot;&#xD;&#xA;" />
  </Target>

</Project>