<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>UPPERIOC</RootNamespace>
    <LangVersion>preview</LangVersion>

        <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
  </PropertyGroup>
	<Import Project="$(MSBuildThisFileDirectory)targets\upperioc.targets" />
	<Import Project="$(MSBuildThisFileDirectory)targets\upperioc.props" />
	<ItemGroup>
	  <Compile Remove="bin\**" />
	  <EmbeddedResource Remove="bin\**" />
	  <None Remove="bin\**" />
	</ItemGroup>
	<ItemGroup>
	  <Compile Remove="UPPER.EmailErrorSender\IErrorConfiguation.cs" />
	</ItemGroup>

	  <ItemGroup>
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Management" Version="4.6.0" />
  </ItemGroup>


<PropertyGroup>
  <Version>2.0.4.43</Version>
  <PackageId>UPPERIOC</PackageId>
  <Authors>Wwwwww</Authors>
  <Description>一个自带插件的IOC容器</Description>
</PropertyGroup>
<ItemGroup Label="Package">

    <None Include="targets\upperioc.targets" PackagePath="build\netstandard2.0" Pack="true" />
    <None Include="targets\upperioc.props" PackagePath="build\netstandard2.0" Pack="true" />
   <None Include="targets\upperioc.targets" PackagePath="buildTransitive\netstandard2.0" Pack="true" />
    <None Include="targets\upperioc.props" PackagePath="buildTransitive\netstandard2.0" Pack="true" />

    
  <None Include="..\IOCCodeGenerator\bin\$(Configuration)\netstandard2.0\IOCCodeGenerator.dll">
    <Pack>true</Pack>
    <PackagePath>analyzers\dotnet\roslyn3.8\cs</PackagePath>
  </None>

    
  <None Remove="..\UPPERIOC\bin\Debug\netstandard2.0\UPPERIOC.dll" />
  <None Include="..\UPPERIOC\bin\$(Configuration)\netstandard2.0\UPPERIOC.dll">
    <Pack>true</Pack>
    <PackagePath>analyzers\dotnet\roslyn3.8\cs</PackagePath>
  </None>
  <None Remove="..\UPPERIOC\bin\Debug\netstandard2.0\UPPERIOC.dll" />
  <None Remove="..\UPPERIOC\bin\Debug\netstandard2.0\UPPERIOC.dll" />
  <None Include="..\UPPERIOC\bin\$(Configuration)\netstandard2.0\UPPERIOC.dll" Pack="true" PackagePath="lib\netstandard2.0" />
  <None Include="..\UPPERIOC\UPPERIOC.png" Pack="true" />
  <None Remove="..\UPPERIOC\bin\Debug\net462\UPPERIOC.dll" />
    <None Include="..\UPPERIOC\bin\$(Configuration)\net462\UPPERIOC.dll" Pack="true" PackagePath="lib\net462" />
</ItemGroup>
  <ItemGroup>

    <ProjectReference Include="..\IOCCodeGenerator\IOCCodeGenerator.csproj" ReferenceOutputAssembly="false" />
   </ItemGroup>


		
	<PropertyGroup>
  <IncludeBuildOutput>true</IncludeBuildOutput>
  <IsRoslynAnalyzer>true</IsRoslynAnalyzer>
  <SignAssembly>True</SignAssembly>
  <PackageLicenseExpression>MIT</PackageLicenseExpression>
  <EnableNETAnalyzers>True</EnableNETAnalyzers>
  <AnalysisLevel>latest</AnalysisLevel>
  <Nullable>enable</Nullable>
  <PackageOutputPath>C:\Program Files (x86)\Microsoft SDKs\NuGetPackages</PackageOutputPath>
  <Title>UPPERIOC</Title>
  <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  <IncludeSymbols>true</IncludeSymbols>
  <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  <PackageReadmeFile>README.md</PackageReadmeFile>
  <PackAsTool>False</PackAsTool>
  <PackageProjectUrl>https://gitee.com/laowangm_m/upper-com-auto-test</PackageProjectUrl>
  <PackageIcon>UPPERIOC.png</PackageIcon>
  <RepositoryUrl>https://gitee.com/laowangm_m/upper-com-auto-test</RepositoryUrl>
  <RepositoryType>gitee</RepositoryType>
  <PackageTags>ioc</PackageTags>
  <PackageReleaseNotes>初始版本</PackageReleaseNotes>
  <ImplicitUsings>enable</ImplicitUsings>
  <NuGetAudit>False</NuGetAudit>
  <AssemblyVersion>2.0.0</AssemblyVersion>
  <UserSecretsId>5d9e1ecd-9e2e-4d37-86f4-fcb71f419384</UserSecretsId>
  <NeutralLanguage>zh</NeutralLanguage>
  <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net461|AnyCPU'">
  <DebugType>embedded</DebugType>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net461|AnyCPU'">
  <DebugType>embedded</DebugType>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net462|AnyCPU'">
  <DebugType>embedded</DebugType>
  <Optimize>True</Optimize>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net462|AnyCPU'">
  <DebugType>embedded</DebugType>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
  <Optimize>True</Optimize>
  <DebugType>embedded</DebugType>
</PropertyGroup>
<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
  <DebugType>embedded</DebugType>
</PropertyGroup>
<ItemGroup>
  <None Include="..\README.md">
    <Pack>True</Pack>
    <PackagePath>\</PackagePath>
  </None>
</ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.2\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="UPPERIOC.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="start /B nuget push  &quot;$(PackageOutputPath)\$(PackageId).$(Version).nupkg&quot;  -Source &quot;http://8.138.99.154:5000/v3/index.json&quot; -ApiKey &quot;wspwasnl001112&quot; || echo &quot;NuGet push failed. Continuing...&quot;&#xD;&#xA;echo &quot;Code generation step starts here...&quot;&#xD;&#xA;" />
  </Target>
</Project>
